In [24]:
import numpy as np

In [25]:
np.__version__

'2.4.4'

In [26]:
import sys 
sys.version

'3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]'

# Creating List

In [5]:
my_list = [0,1,2,3,4,5,6]
my_list

[0, 1, 2, 3, 4, 5, 6]

In [6]:
type(my_list)

list

# Below code we are converting list to array

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
type(arr)

numpy.ndarray

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5,dtype=int) # 1d Array

array([0, 0, 0, 0, 0])

In [15]:
np.zeros((2,2),dtype=int) # 2d Array

array([[0, 0],
       [0, 0]])

In [16]:
np.zeros((5,7),dtype=int) # nd Array

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.ones((5,7),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [20]:
np.random.rand(5)

array([0.38347057, 0.74347184, 0.1993304 , 0.03173131, 0.401786  ])

In [21]:
np.random.rand(2,3)

array([[0.76182212, 0.99514713, 0.146823  ],
       [0.50770693, 0.56570655, 0.82925397]])

In [22]:
np.random.random(4)

array([0.82462813, 0.28476857, 0.55033882, 0.63194873])

In [23]:
np.random.random((2,3))

array([[0.59324036, 0.01088593, 0.40967681],
       [0.05414359, 0.59454084, 0.40549051]])

In [24]:
np.random.randint(10) # random number between 1 to 10

1

In [25]:
np.random.randint(20,100) # random number between 20 to 100

33

In [26]:
np.random.randint(20,100,5) #--> (lowestNumber,HighestNumber,SizeOfNumbers)

array([57, 71, 98, 65, 90], dtype=int32)

In [27]:
np.random.randint(10,1,3) # low >= high , we cannot genrate high value to low value integer 

ValueError: low >= high

In [ ]:
np.random.randint(-10,10,3)

In [28]:
np.random.randint(1,20,(5,5))

array([[17,  7,  2, 18, 13],
       [ 6, 18, 10, 12, 12],
       [ 3,  4, 10, 11,  8],
       [ 3,  7,  8, 17,  5],
       [15, 12, 12, 12,  4]], dtype=int32)

In [29]:
ri = np.random.randint(10,50,(10,10))
ri

array([[23, 27, 11, 29, 18, 33, 41, 41, 26, 32],
       [14, 15, 33, 32, 40, 14, 15, 42, 37, 16],
       [37, 39, 35, 11, 19, 30, 49, 32, 32, 21],
       [35, 35, 44, 43, 30, 26, 38, 24, 32, 26],
       [45, 30, 20, 43, 37, 20, 30, 20, 12, 19],
       [46, 19, 14, 29, 12, 22, 32, 32, 31, 16],
       [30, 46, 34, 34, 11, 35, 12, 41, 33, 21],
       [31, 33, 42, 40, 19, 44, 30, 48, 19, 47],
       [10, 48, 32, 28, 49, 22, 19, 17, 12, 22],
       [31, 15, 29, 25, 23, 45, 30, 10, 38, 20]], dtype=int32)

In [30]:
len(ri) # it will print by default number of rows 

10

In [31]:
ri.shape # it ruteun the given Nd array or matrix --> (row,columan)

(10, 10)

In [32]:
id(ri) # Memory Location of The Given Nd Arraay

2737803813456

# Slicing in numpy 

In [33]:
ri[:] # Print All

array([[23, 27, 11, 29, 18, 33, 41, 41, 26, 32],
       [14, 15, 33, 32, 40, 14, 15, 42, 37, 16],
       [37, 39, 35, 11, 19, 30, 49, 32, 32, 21],
       [35, 35, 44, 43, 30, 26, 38, 24, 32, 26],
       [45, 30, 20, 43, 37, 20, 30, 20, 12, 19],
       [46, 19, 14, 29, 12, 22, 32, 32, 31, 16],
       [30, 46, 34, 34, 11, 35, 12, 41, 33, 21],
       [31, 33, 42, 40, 19, 44, 30, 48, 19, 47],
       [10, 48, 32, 28, 49, 22, 19, 17, 12, 22],
       [31, 15, 29, 25, 23, 45, 30, 10, 38, 20]], dtype=int32)

In [34]:
ri[1] # Print First Row

array([14, 15, 33, 32, 40, 14, 15, 42, 37, 16], dtype=int32)

In [35]:
ri[0:3] # here 3 means 3-1 = 2

array([[23, 27, 11, 29, 18, 33, 41, 41, 26, 32],
       [14, 15, 33, 32, 40, 14, 15, 42, 37, 16],
       [37, 39, 35, 11, 19, 30, 49, 32, 32, 21]], dtype=int32)

In [36]:
print(ri)

[[23 27 11 29 18 33 41 41 26 32]
 [14 15 33 32 40 14 15 42 37 16]
 [37 39 35 11 19 30 49 32 32 21]
 [35 35 44 43 30 26 38 24 32 26]
 [45 30 20 43 37 20 30 20 12 19]
 [46 19 14 29 12 22 32 32 31 16]
 [30 46 34 34 11 35 12 41 33 21]
 [31 33 42 40 19 44 30 48 19 47]
 [10 48 32 28 49 22 19 17 12 22]
 [31 15 29 25 23 45 30 10 38 20]]


In [37]:
ri[3:8]

array([[35, 35, 44, 43, 30, 26, 38, 24, 32, 26],
       [45, 30, 20, 43, 37, 20, 30, 20, 12, 19],
       [46, 19, 14, 29, 12, 22, 32, 32, 31, 16],
       [30, 46, 34, 34, 11, 35, 12, 41, 33, 21],
       [31, 33, 42, 40, 19, 44, 30, 48, 19, 47]], dtype=int32)

In [38]:
ri[3,8] # --> we specifically find out the 3 row or 8 clouman index it will return that value (28)

np.int32(32)

 - [[48 35 17 29 49 22 20 24 16 40]
 -  [38 14 31 49 38 26 31 10 29 25]
 -  [42 47 40 31 34 22 12 14 40 47]
 -  [32 35 44 48 37 48 17 44 28 18] --> 28 returun
 -  [21 12 19 43 14 38 16 19 20 46]
 -  [39 43 37 44 12 49 27 28 18 47]
 -  [10 28 44 46 10 10 31 25 31 43]
 -  [28 30 14 35 45 18 44 27 19 42]
 -  [49 19 45 11 32 20 22 13 47 18]
 -  [19 49 49 11 37 30 41 22 23 46]]

In [39]:
ri[-5]

array([46, 19, 14, 29, 12, 22, 32, 32, 31, 16], dtype=int32)

In [40]:
ri[-5,-3]

np.int32(32)

In [41]:
ri[::3]

array([[23, 27, 11, 29, 18, 33, 41, 41, 26, 32],
       [35, 35, 44, 43, 30, 26, 38, 24, 32, 26],
       [30, 46, 34, 34, 11, 35, 12, 41, 33, 21],
       [31, 15, 29, 25, 23, 45, 30, 10, 38, 20]], dtype=int32)

In [42]:
ri[::-1]

array([[31, 15, 29, 25, 23, 45, 30, 10, 38, 20],
       [10, 48, 32, 28, 49, 22, 19, 17, 12, 22],
       [31, 33, 42, 40, 19, 44, 30, 48, 19, 47],
       [30, 46, 34, 34, 11, 35, 12, 41, 33, 21],
       [46, 19, 14, 29, 12, 22, 32, 32, 31, 16],
       [45, 30, 20, 43, 37, 20, 30, 20, 12, 19],
       [35, 35, 44, 43, 30, 26, 38, 24, 32, 26],
       [37, 39, 35, 11, 19, 30, 49, 32, 32, 21],
       [14, 15, 33, 32, 40, 14, 15, 42, 37, 16],
       [23, 27, 11, 29, 18, 33, 41, 41, 26, 32]], dtype=int32)

In [44]:
ri

array([[23, 27, 11, 29, 18, 33, 41, 41, 26, 32],
       [14, 15, 33, 32, 40, 14, 15, 42, 37, 16],
       [37, 39, 35, 11, 19, 30, 49, 32, 32, 21],
       [35, 35, 44, 43, 30, 26, 38, 24, 32, 26],
       [45, 30, 20, 43, 37, 20, 30, 20, 12, 19],
       [46, 19, 14, 29, 12, 22, 32, 32, 31, 16],
       [30, 46, 34, 34, 11, 35, 12, 41, 33, 21],
       [31, 33, 42, 40, 19, 44, 30, 48, 19, 47],
       [10, 48, 32, 28, 49, 22, 19, 17, 12, 22],
       [31, 15, 29, 25, 23, 45, 30, 10, 38, 20]], dtype=int32)

In [45]:
ri[:,2] # we Get 2 Number columan Value

array([11, 33, 35, 44, 20, 14, 34, 42, 32, 29], dtype=int32)

In [48]:
print(ri[2]) # 2 Row 
print(ri[:,2]) # 2 Columan

[37 39 35 11 19 30 49 32 32 21]
[11 33 35 44 20 14 34 42 32 29]


In [49]:
print(ri[:,-2]) 

[26 37 32 32 12 31 33 19 12 38]


In [53]:
print(ri[:-4:,1])

[27 15 39 35 30 19]


## Q. Extract The Specific Matrix

In [78]:
ri

array([[23, 27, 11, 29, 18, 33, 41, 41, 26, 32],
       [14, 15, 33, 32, 40, 14, 15, 42, 37, 16],
       [37, 39, 35, 11, 19, 30, 49, 32, 32, 21],
       [35, 35, 44, 43, 30, 26, 38, 24, 32, 26],
       [45, 30, 20, 43, 37, 20, 30, 20, 12, 19],
       [46, 19, 14, 29, 12, 22, 32, 32, 31, 16],
       [30, 46, 34, 34, 11, 35, 12, 41, 33, 21],
       [31, 33, 42, 40, 19, 44, 30, 48, 19, 47],
       [10, 48, 32, 28, 49, 22, 19, 17, 12, 22],
       [31, 15, 29, 25, 23, 45, 30, 10, 38, 20]], dtype=int32)

In [89]:
# 14, 29, 12, 22, 32 --> Access This 
ri[5,2:7]

array([14, 29, 12, 22, 32], dtype=int32)

In [92]:
# [12]
# [11]
# [19]
# [49]
ri[5:9,4]

array([12, 11, 19, 49], dtype=int32)

In [93]:
# [[23, 27, 11, 29],
#  [14, 15, 33, 32],
#  [37, 39, 35, 11],
#  [35, 35, 44, 43]]
ri[0:4,0:4]

array([[23, 27, 11, 29],
       [14, 15, 33, 32],
       [37, 39, 35, 11],
       [35, 35, 44, 43]], dtype=int32)

In [94]:
# [[11, 19, 30, 49],
#  [43, 30, 26, 38],
#  [43, 37, 20, 30],
#  [29, 12, 22, 32]]
ri[2:6,3:7]

array([[11, 19, 30, 49],
       [43, 30, 26, 38],
       [43, 37, 20, 30],
       [29, 12, 22, 32]], dtype=int32)

In [ ]:
# [[11, 19, 30, 49],
#  [43, 30, 26, 38],
#  [43, 37, 20, 30],
#  [29, 12, 22, 32]]

In [111]:
ri[2:6,4:6]

array([[19, 30],
       [30, 26],
       [37, 20],
       [12, 22]], dtype=int32)

In [116]:
# print the reverse matrix
ri[2:6,4:6]

array([[19, 30],
       [30, 26],
       [37, 20],
       [12, 22]], dtype=int32)

In [120]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
np.arange(1,13).reshape(5,4) # ValueError because the 5*4 = 20 value approxmetly we want . but actucal the size is 12 

ValueError: cannot reshape array of size 12 into shape (5,4)

In [124]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [132]:
np.arange(1,13).reshape(3,1) # --> Still erroe beacuse the 3*1 = 3 but we want the 12 size . It only reshape were value row*columan = SizeOfValues 

ValueError: cannot reshape array of size 12 into shape (3,1)

In [133]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [134]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [135]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [137]:
np.arange(1,13).reshape(6,2) # All Factors of 12 is applicable row * columan

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [140]:
print(ri.max())

49


In [143]:
print(ri.min())

10


In [141]:
print(ri.mean())

28.81


In [144]:
print(ri.median())

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [27]:
from numpy import *  # 256 function call internally
print(median(ri))

NameError: name 'ri' is not defined

In [157]:
mod

TypeError: remainder() takes from 2 to 3 positional arguments but 1 was given

In [162]:
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [163]:
arr.reshape(4,3,order='C')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [164]:
arr.reshape(4,3,order='F') # Print element with fortran

array([[ 1,  6, 11],
       [ 5, 10,  4],
       [ 9,  3,  8],
       [ 2,  7, 12]])

In [168]:
arr.reshape(4,3,order='A') # A almost give you C Type Output

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [169]:
arr1 = np.arange(100).reshape(20,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [173]:
print("F type of Array")
for i in np.nditer(arr1,order='F'):
    print(i,end=" ")

C type of Array
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 1 6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96 2 7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97 3 8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98 4 9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99 

In [174]:
print("C type of Array")
for i in np.nditer(arr1,order='C'):
    print(i,end=" ")

C type of Array
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [175]:
print("F type of Array")
for i in np.nditer(arr1,order='A'):
    print(i,end=" ")

F type of Array
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

### numpy masking and Filters

In [4]:
mat = np.arange(100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
id(mat) # identity of Obj

2311890955856

In [6]:
mat.shape

(10, 10)

In [7]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [8]:
mat[mat < 50] # when we write two time mat then it is called mask and filtering

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
mat[mat <= 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [10]:
mat[mat == 50]

array([50])

In [11]:
mat[mat >= 50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
# Create Indetity Matrix --> All digonal are 1
f = np.eye(4) # 4 x 4 identity matrix
print("Identity Matrix : \n",f)

Identity Matrix : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
i = np.identity(4) # 4 x 4 identity matrix
print("Identity Matrix : \n",i)

Identity Matrix : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manapulation Functions

In [36]:
from numpy import *

# Reshape an array
a1 = np.array([1,2,3,4]) 
a1

array([1, 2, 3, 4])

In [48]:
# Flatten an array
f1 = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
flattened = np.ravel(f1) # Return a contiguous flattened array. 1D array
print("Flattened array : ",flattened)

Flattened array :  [1 2 3 4 5 6 7 8]


In [50]:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) # it convert row into columan or columan into row
transposed
# For a 1-D array, this returns an unchanged view of the original array, as a
# transposed vector is simply the same vector.

array([[1, 3],
       [2, 4]])

In [56]:
a1 = np.array([1,2])
b1 = np.array([3,4])
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a1,b1,a2,b2]) # Stack arrays in sequence vertically (row wise) 
stacked

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [55]:
a1 = np.array([1,2])
b1 = np.array([3,4])
stacked = np.hstack([a1,b1]) # Stack arrays in sequence horizontally (column wise).
stacked

array([1, 2, 3, 4])

# Mathamaical Function

In [57]:
# Add Two Array
g = np.array([1,2,3,4,5,6])
added = np.add(g,2) # add each element by 2
added

array([3, 4, 5, 6, 7, 8])

In [59]:
# Square of each element
squared = np.power(g,2)
squared

array([ 1,  4,  9, 16, 25, 36])

In [60]:
# Square root of each element
sqrt = np.sqrt(g)
sqrt

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [66]:
a1 = np.array([1,2,3,4,5,6])


In [67]:
a1

array([1, 2, 3, 4, 5, 6])

In [68]:
g

array([1, 2, 3, 4, 5, 6])

In [70]:
dot_product = np.dot(a1,g)
print(dot_product)

91
